title: Алексей Мерзляков
description: Личный сайт Алексея Мерзлякова.
url: "" # site url
baseurl: "alvmer.github.io" # apply repo name if use it under gh-pages branch

repo: https://github.com/alvmer/alvmer.github.io
comments: false

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-spaceship

assets:
   sources:
       -_assets/fonts

# Build settings
permalink   : /:categories/:year/:month/:day/:title:output_ext
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Author settings
author:
  name     : "Alexey Merzlyakov"

# social settings
og_locale: "ru_RU"

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3

exclude: ["vendor", "Gemfile", "Gemfile.lock", "README.md", "LICENSE.txt", "Rakefile", "netlify.toml"]
